---
- name: "OS Family:"
  debug:
    msg: "{{ansible_os_family}}"

# - name: Ensure docker is called via binary path on MACOS
- name: Setting docker path fact if OS is MacOS
  ansible.builtin.set_fact:
    docker_path: "{% if ansible_facts['os_family']=='Darwin' %}{{docker_path_mac}}{% endif %}"

# Changed this from a service check to a shell check to support MacOS and WSL2
- name: "Ensure docker is running"
  shell: > 
          {{docker_path}}docker ps
  failed_when: > 
    (wsadmin_output.stderr != '')
  register: wsadmin_output

# - debug:
#     msg: "{{wsadmin_output}}"

# - meta: end_play